### ISSUE TITLE
Custom user with dash generate an error.

### ISSUE THREAD

**Issue by keyandcloud** [nanobox-io/nanobox-docker-mysql#33]
Hello, After adding the user to the database, I get an error when starting nanobox. In my case i can not use another name.

```
Error: '/data/var/home/gonano/.bashrc: line 28: export: `DATA_MYSQL_KAC-USER_PASS=ALD91fkYJn': not a valid identifier'
```

```
nanobox run
...
/data/var/home/gonano/.bashrc: line 28: export: `DATA_MYSQL_KAC-USER_PASS=ALD91fkYJn': not a valid identifier
bash: export: `DATA_MYSQL_KAC-USER_PASS=ALD91fkYJn': not a valid identifier

```

My configuration

```
data.mysql:
  image: nanobox/mysql:5.6
  config:
    users:
      - username: root
        meta:
          privileges:
            - privilege: ALL PRIVILEGES
              'on': "*.*"
              with_grant: true
      - username: kac-user
```
